name: Daily Cleanup

on:
  schedule:
    - cron: '30 2 * * *'  # This means the action will run at 02:30 AM UTC every day
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: windows-latest

    steps:
      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false

      - name: Ensure AzureRM module is installed
        shell: pwsh
        run: |
          # Check if AzureRM module is installed
          if (-not (Get-Module -ListAvailable -Name AzureRM)) {
              Write-Host "AzureRM module not found. Installing AzureRM module..."
              Install-Module -Name AzureRM -AllowClobber -Force
          } else {
              Write-Host "AzureRM module is already installed."
          }

      - name: Run cleanup script
        shell: pwsh
        run: |
          # Import AzureRM module
          Import-Module AzureRM
          
          # Define the subscription ID
          $subscriptionId = "2d0b03c0-875c-46fa-9993-32a30821afc5"
          
          # Connect to Azure account (handled by azure/login action)
          Write-Host "Logged in to Azure with Service Principal"
          
          # Set the context to the specified subscription
          Write-Host "Selecting subscription $subscriptionId..."
          Select-AzureRmSubscription -SubscriptionId $subscriptionId
          
          # Function to delete all resource groups and wait for completion
          function Delete-AllResourceGroups {
              Write-Host "Retrieving all resource groups in the subscription..."
              $resourceGroups = Get-AzureRmResourceGroup
              $jobs = @()
              foreach ($rg in $resourceGroups) {
                  Write-Host "Deleting resource group $($rg.ResourceGroupName)..."
                  $jobs += Remove-AzureRmResourceGroup -Name $rg.ResourceGroupName -Force -AsJob
              }
              # Wait for all jobs to complete
              foreach ($job in $jobs) {
                  $job | Wait-Job
              }
          }
          
          # Function to delete all deployments and wait for completion
          function Delete-AllDeployments {
              Write-Host "Retrieving all deployments in the subscription..."
              $deployments = Get-AzureRmDeployment
              foreach ($deployment in $deployments) {
                  Write-Host "Deleting deployment $($deployment.DeploymentName)..."
                  Remove-AzureRmDeployment -Name $deployment.DeploymentName -Force
              }
          }
          
          # Function to delete all role assignments and wait for completion
          function Delete-AllRoleAssignments {
              Write-Host "Retrieving all role assignments in the subscription..."
              $roleAssignments = Get-AzureRmRoleAssignment
              foreach ($roleAssignment in $roleAssignments) {
                  Write-Host "Deleting role assignment $($roleAssignment.Name)..."
                  Remove-AzureRmRoleAssignment -ObjectId $roleAssignment.ObjectId -RoleDefinitionName $roleAssignment.RoleDefinitionName -Scope $roleAssignment.Scope
              }
          }
          
          # Function to delete all policies and wait for completion
          function Delete-AllPolicies {
              Write-Host "Retrieving all policies in the subscription..."
              $policies = Get-AzureRmPolicyAssignment
              foreach ($policy in $policies) {
                  Write-Host "Deleting policy $($policy.Name)..."
                  Remove-AzureRmPolicyAssignment -Name $policy.Name -Scope $policy.Scope
              }
          }
          
          # Function to delete orphaned resources and wait for completion
          function Delete-AllOrphanedResources {
              Write-Host "Retrieving all resources in the subscription..."
              $resources = Get-AzureRmResource
              foreach ($resource in $resources) {
                  Write-Host "Deleting resource $($resource.Name) in group $($resource.ResourceGroupName)..."
                  $apiVersion = (Get-AzureRmResourceProvider -ProviderNamespace $resource.ResourceType.Split('/')[0]).ResourceTypes | Where-Object ResourceTypeName -eq $resource.ResourceType.Split('/')[1] | Select-Object -ExpandProperty ApiVersions | Sort-Object -Descending | Select-Object -First 1
                  Remove-AzureRmResource -ResourceId $resource.ResourceId -Force -ApiVersion $apiVersion
              }
          }
          
          # Execute all delete functions and wait for completion
          Delete-AllResourceGroups
          Delete-AllDeployments
          Delete-AllRoleAssignments
          Delete-AllPolicies
          Delete-AllOrphanedResources
          
          # Final check to ensure everything is deleted
          Write-Host "Final check to ensure all resources are deleted..."
          $remainingResources = Get-AzureRmResource
          if ($remainingResources) {
              Write-Host "Some resources could not be deleted:"
              $remainingResources | Format-Table -Property Name, ResourceGroupName, ResourceType, Location
          } else {
              Write-Host "All resources have been successfully deleted."
          }
          
          Write-Host "All resources, deployments, role assignments, and policies have been deleted. Monitor the Azure portal for any remaining resources."
