name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure App Service
        run: |
          az group create --name myResourceGroup --location eastus
          az appservice plan create --name myAppServicePlan --resource-group myResourceGroup --sku FREE
          az webapp create --name myWebApp --resource-group myResourceGroup --plan myAppServicePlan

      - name: Configure database connection string and app settings
        run: |
          connStr=$(az sql db show-connection-string --name myDatabase --server mySqlServer --client ado.net)
          az webapp config connection-string set --resource-group myResourceGroup --name myWebApp --settings DefaultConnection=$connStr --connection-string-type SQLAzure
          az webapp config appsettings set --resource-group myResourceGroup --name myWebApp --settings DB_USER=myAdmin DB_PASSWORD=MyP@ssword1234 DB_SERVER=mySqlServer.database.windows.net DB_NAME=myDatabase

      - name: Deploy to Azure Web App
        run: |
          cd server
          zip -r ../myapp.zip .
          cd ..
          az webapp deploy --resource-group myResourceGroup --name myWebApp --src-path myapp.zip --type zip
