name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Create Azure resources
        run: |
          az group create --name myResourceGroup --location eastus
          az appservice plan create --name myAppServicePlan --resource-group myResourceGroup --sku FREE
          az webapp create --name myWebApp --resource-group myResourceGroup --plan myAppServicePlan
          az sql server create --name mySqlServer --resource-group myResourceGroup --location eastus --admin-user myAdmin --admin-password MyP@ssword1234
          az sql db create --resource-group myResourceGroup --server mySqlServer --name myDatabase --service-objective S0

      - name: Configure database connection string
        run: |
          connStr=$(az sql db show-connection-string --name myDatabase --server mySqlServer --client ado.net)
          az webapp config connection-string set --resource-group myResourceGroup --name myWebApp --settings DefaultConnection=$connStr --connection-string-type SQLAzure

      - name: Deploy to Azure Web App
        run: |
          zip -r myapp.zip .
          az webapp deploy --resource-group myResourceGroup --name myWebApp --src-path myapp.zip --type zip

