name: Uninstall AzureRM

on:
  workflow_dispatch:

jobs:
  uninstall-azurerm:
    runs-on: windows-latest

    steps:
      - name: Uninstall AzureRM Modules
        shell: pwsh
        run: |
          # Uninstall AzureRM module if it exists
          if (Get-Module -ListAvailable -Name AzureRM) {
              Write-Host "AzureRM module found. Uninstalling AzureRM module..."
              Uninstall-Module -Name AzureRM -AllVersions -Force -ErrorAction SilentlyContinue
          } else {
              Write-Host "AzureRM module not found."
          }
