name: Set Up Database

on:
  push:
    branches:
      - main

jobs:
  setup-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create SQL server and database
        id: create-db
        run: |
          DB_NAME='llamatestingdatabasefor3-1'
          DB_SERVER='llamatestingdatabasefor3-1'
          RESOURCE_GROUP='demoResourceGroup'
          ADMIN_USER='myAdmin'
          ADMIN_PASSWORD='MyP@ssword1234'
          LOCATION='centralus'

          echo "Creating SQL server..."
          az sql server create --name $DB_SERVER --resource-group $RESOURCE_GROUP --location $LOCATION --admin-user $ADMIN_USER --admin-password $ADMIN_PASSWORD

          echo "Setting firewall rule to allow all IPs..."
          az sql server firewall-rule create --resource-group $RESOURCE_GROUP --server $DB_SERVER --name AllowAllIps --start-ip-address 0.0.0.0 --end-ip-address 255.255.255.255

          echo "Creating SQL database..."
          az sql db create --resource-group $RESOURCE_GROUP --server $DB_SERVER --name $DB_NAME --service-objective S0

          # Save credentials to environment variables
          echo "Saving credentials to environment variables..."
          echo "DB_USER=$ADMIN_USER" >> $GITHUB_ENV
          echo "DB_PASSWORD=$ADMIN_PASSWORD" >> $GITHUB_ENV
          echo "DB_SERVER=$DB_SERVER.database.windows.net" >> $GITHUB_ENV
          echo "DB_NAME=$DB_NAME" >> $GITHUB_ENV

      - name: Save database credentials
        run: |
          echo "Saving database credentials..."
          echo "${{ env.DB_USER }}" > db_user.txt
          echo "${{ env.DB_PASSWORD }}" > db_password.txt
          echo "${{ env.DB_SERVER }}" > db_server.txt
          echo "${{ env.DB_NAME }}" > db_name.txt

      - name: Upload database credentials
        uses: actions/upload-artifact@v2
        with:
          name: db-credentials
          path: |
            db_user.txt
            db_password.txt
            db_server.txt
            db_name.txt
